In [2]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])

In [3]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
x.dtype

dtype('int32')

In [5]:
x.shape

(5,)

In [7]:
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
y.shape

(4, 3)

In [9]:
y.size

12