In [3]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
np.array(my_list)

array([1, 2, 3, 4, 5])

In [9]:
X = np.zeros((3, 4), dtype=int)
print(X)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [10]:
print('dtype:', X.dtype)

dtype: int32


In [11]:
X = np.ones((4, 5))
print(X)

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


In [13]:
X = np.full((4, 3), 5)
print(X)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [14]:
print(X.dtype)

int32


In [15]:
X = np.eye(5)
print(X)

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [16]:
X = np.diag((10, 20, 30, 50))
print(X)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]


In [18]:
X = np.arange(10)
print(X)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
X = np.arange(4,10)
print(X)

[4 5 6 7 8 9]


In [21]:
x = np.arange(1, 14, 3)
print(x)

[ 1  4  7 10 13]


In [22]:
x = np.linspace(0, 25, 10)
print(x)

[  0.           2.77777778   5.55555556   8.33333333  11.11111111
  13.88888889  16.66666667  19.44444444  22.22222222  25.        ]


In [24]:
x = np.linspace(0, 25, 10, endpoint=False)
print(x)

[  0.    2.5   5.    7.5  10.   12.5  15.   17.5  20.   22.5]


In [26]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [27]:
x = np.reshape(x, (4,5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [28]:
x = np.reshape(x, (10,2))
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [30]:
Y = np.arange(20).reshape((10,2))
print(Y)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [31]:
X = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)
print(X)

[[  0.   5.]
 [ 10.  15.]
 [ 20.  25.]
 [ 30.  35.]
 [ 40.  45.]]


In [32]:
x = np.random.random((3, 3))
print(x)

[[ 0.54332385  0.71883253  0.42453853]
 [ 0.42440936  0.24257512  0.27441787]
 [ 0.17982599  0.82025742  0.06229421]]


In [34]:
X = np. random.randint(4, 15, (3, 2))
print(X)

[[10 11]
 [10 14]
 [10  9]]


In [37]:
X = np.random.normal(0, 0.1, size=(1000, 1000)) # mean is 0, standard dev is 0.1
print(X)

[[ 0.21404254 -0.05424108 -0.01837649 ...,  0.04716358 -0.02645117
   0.00610352]
 [ 0.09460434  0.00567262  0.11349025 ..., -0.12884152 -0.0433036
   0.04714375]
 [ 0.12651867  0.01728796  0.00856502 ...,  0.04824914 -0.08382688
  -0.09651738]
 ..., 
 [-0.04809881  0.0014998  -0.09363372 ..., -0.03268687 -0.16360875
  -0.13280179]
 [ 0.06131968  0.17993829 -0.06548041 ..., -0.03040355  0.12140494
   0.13730022]
 [ 0.09544168  0.05739315 -0.03875644 ..., -0.04157763 -0.13778145
  -0.02386294]]


In [39]:
print('mean:', X.mean())
print('std:', X.std())

mean: -0.000224952304946
std: 0.100078078224


In [48]:
X = np.zeros((3, 4))
print(X,"\n")
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The element in X are of type:', X.dtype)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]] 

X has dimensions: (3, 4)
X is an object of type: <class 'numpy.ndarray'>
The element in X are of type: float64
