In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
print(x)
print(y)

[1 2 3 4]
[5 6 7 8]


In [3]:
print(x + y)
print(np.add(x, y))

[ 6  8 10 12]
[ 6  8 10 12]


In [4]:
print(x - y)
print(np.subtract(x, y))
print(x * y)
print(np.multiply(x, y))
print(x / y)
print(np.divide(x, y))

[-4 -4 -4 -4]
[-4 -4 -4 -4]
[ 5 12 21 32]
[ 5 12 21 32]
[ 0.2         0.33333333  0.42857143  0.5       ]
[ 0.2         0.33333333  0.42857143  0.5       ]


In [5]:
X = np.array([1, 2, 3, 4]).reshape(2, 2)
print(X)

Y = np.array([5, 6, 7, 8]).reshape(2, 2)
print(Y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [6]:
print(X + Y)

[[ 6  8]
 [10 12]]


In [7]:
print(X - Y)

[[-4 -4]
 [-4 -4]]


In [8]:
print(X * Y)
print(X / Y)

[[ 5 12]
 [21 32]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [9]:
print(x)
print(np.sqrt(x))

[1 2 3 4]
[ 1.          1.41421356  1.73205081  2.        ]


In [10]:
print(np.exp(x))

[  2.71828183   7.3890561   20.08553692  54.59815003]


In [11]:
print(np.power(x, 2))

[ 1  4  9 16]


In [13]:
print(X)
print('average of all:', X.mean())
print('average of columns:', X.mean(axis=0))
print('average of rows:', X.mean(axis=1))


[[1 2]
 [3 4]]
average of all: 2.5
average of columns: [ 2.  3.]
average of rows: [ 1.5  3.5]


In [14]:
print('sum of all:', X.sum())
print('sum of columns:', X.sum(axis=0))
print('sum of rows:', X.sum(axis=1))

sum of all: 10
sum of columns: [4 6]
sum of rows: [3 7]


In [15]:
X.std()

1.1180339887498949

In [18]:
np.median(X)

2.5

In [19]:
X.max()

4

In [21]:
X.min()

1

In [22]:
print(X)

[[1 2]
 [3 4]]


In [23]:
print(3 + X)

[[4 5]
 [6 7]]


In [24]:
print(3 - X)
print(3 * X)
print(3 / X)

[[ 2  1]
 [ 0 -1]]
[[ 3  6]
 [ 9 12]]
[[ 3.    1.5 ]
 [ 1.    0.75]]


In [25]:
Y = np.arange(9).reshape(3, 3)
print(Y)
x = np.arange(3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


In [26]:
print(Y + x)


[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [27]:
print(x + Y)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [28]:
z = np.arange(3).reshape(3, 1)
print(z)

[[0]
 [1]
 [2]]


In [29]:
print(z + Y)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
